<html>
    <head>
        <link rel="stylesheet" type="text/css" href="addpost.css">
        <script src="https://kit.fontawesome.com/f770f9bca0.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&family=Satisfy&family=Shadows+Into+Light&family=Work+Sans:ital,wght@1,200&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/f770f9bca0.js" crossorigin="anonymous"></script>
<style>
    * {
    margin: 0;
    padding: 0;
    font-family: 'Dancing Script', cursive;
    font-family: 'Satisfy', cursive;
font-family: 'Shadows Into Light', cursive;
font-family: 'Work Sans', sans-serif;
    box-sizing: border-box;
}

body {
    background: #e1dddd;

}
.kenburns-top {
	-webkit-animation: kenburns-top 5s ease-out both;
	        animation: kenburns-top 5s ease-out both;
   

}
.kenburns-top img{
    width: 100%;
    height: 90%;
    position:-ms-page;
}


header {
  
    width: 100%;
    height: 90px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    background-color:#000;
    padding: 0 100px;

}

.hamburger {
    display: none;
}

.logo {
    font-family: 'Dancing Script', cursive;
    font-family: 'Satisfy', cursive;
    font-size:30px;
    color: #fbfbfb;
    padding:0.1px;
    -webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
            animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    

}
/* ----------------------------------------------
 * Generated by Animista on 2023-1-28 14:50:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes logo {
    0% {
      -webkit-filter: blur(12px);
              filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
              filter: blur(0px);
      opacity: 1;
    }
  }
  @keyframes logo {
    0% {
      -webkit-filter: blur(12px);
              filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
              filter: blur(0px);
      opacity: 1;
    }
  }
  

nav ul li {

    display: inline-block;
    padding: 0px 18px;
}

nav ul li a {
    color: #fefefe;
    text-decoration: none;
    font-size: 20px;
    display: inline-block;
    border-radius: 23px;
    padding: 10 25px;
    margin: 0 3px;


}
nav ul li a:hover{
    color: black;
    background: #fefefe;

}
nav ul li a.active{
    color: black;
    background: #fefefe;

}
@media only screen and (max-width:1320px){
    header {
        padding:0 50px;
    }
}
@media only screen and(max-width:1100px){
    header {
        padding:0 30px;

    }
}
@media only screen and (max-width:900px){
    .hamburger{
        display:block;
        cursor:pointer;

    }
    .humberger .line{
        width:30px;
        height:3px;
        background: #fefefe;
        margin:6px 0;
    }
}
footer *{
    margin:0;
    padding:0;
    box-sizing: border-box;
}
.footer {
    z-index: -1;
    position: absolute;
    bottom:0;
    width: 100%;
    
    
    
  }
.container{
    z-index: -1;
    margin-bottom: 0%;
    height:170px;
    max-width: 1970px;
    margin:auto;
    background-color:#000000;
    padding-top: 20px;
  
}
.row{
    display: flex;
}
ul{
    list-style: none;
}
ul li a{

    text-decoration: none;
}
footer *{
    margin:0;
    padding:0;
    box-sizing: border-box;
}
.footer {
    z-index: -1;
    position: absolute;
    bottom:0;
    width: 100%;
    
    
    
  }
.container{
    z-index: -1;
    margin-bottom: 0%;
    height:170px;
    max-width: 1970px;
    margin:auto;
    background-color:#24262b;
    padding-top: 20px;
  
}
.row{
    display: flex;
}
ul{
    list-style: none;
}
ul li a{

    text-decoration: none;
   
}

.footer{
 
    padding:70 0px;

}
.footer-col{
    width:25%;
    padding:0 15px; 
}
.footer-col h4{
    font-size:18px;
    color:rgb(255, 254, 254);
    text-transform:capitalize;
    position:relative;
    font-weight:600;
    margin-bottom: 13px;
}
.footer-col h4:before{
    content: " ";
    position:absolute;
    left:0;
    bottom:-10px;
    height:2px;
    background-color:#e91e63;
    box-sizing:border-box;
    width:40px;
}
.footer-col ul li a{
    z-index: -1;
    font-size:16px;
    text-transform:capitalize;
    color:#ffffff;
    text-decoration:none;
    font-weight:300;
    color:#bbbbbb;
    display:block;
    transition:all 0.3 ease;
}
.footer-col ul li a:hover{
    color: #ffffff;
    padding-left:12px;

}
.footer-col .social-links a{
    z-index: -1;
    display: inline-block;
    height:40px;
    width:40px;
    background-color: rgba(19, 18, 18, 0.2);
    text-align:center;
    line-height:10px;
    border-radius: 50%;
    color:#ffffff;
    transition:all 0.5 ease;
    transform: translateY(10px);
    padding:11 10px;
    margin:0 10px 10px 0;

}
.footer-col .social-links a:hover{
    color:black;
    background-color: #ffffff;
}
.header1{
    display: flex;
    border-bottom: 1px solid #666666;
    background-image: url("nature1.svg");
    background-size:450px; /* Ajuste la taille de l'image pour couvrir tout le corps */
    background-position: center;
    }
.oip{
    width:200px;
    height:200px;
    border-radius: 50%;
    margin-left:2%;
    margin-top:1%;
    margin-bottom:1%;

}
.details{
    margin-left:10%;
    margin-top:3%;
    font-size: 40px;
    font-family: 'Almarai', sans-serif;
}
.detail{
    margin-left: 35%;
    font-size: 20px;
    width:800px;
    color: #1c0063;
}
.a{
    margin-right:10px;
}
.ajouter{
    margin-left: 1%;
    margin-top: 1%;
    font-size: 34px;
    padding:5px;
  

    

}
.card{
 
   /* Définir la largeur souhaitée */
    
    margin-top:5%;
    margin-left: 18%;
    

   
   
    border-radius: 20px;
    
    width:800px;
    height:360px;
    background-color: aliceblue;

}

.video-background{
    position: absolute;
    z-index:-1;
    right:0;
    bottom: 0;
    left:0;
    top: 0;
    width:1200px;
    height:500px;
    margin-left: 25px;
    border-radius: 50px;
    margin-top:8%;
}
input {
  width: 240px;
  padding: 12px;
  border: none;
  border-radius: 4px;
  box-shadow: 2px 2px 17px 0 rgb(0, 0, 0, 0.2);
  outline: none;
  color: rgb(0, 0, 0);
  margin:5px;
}

.input:invalid {
  animation: justshake 0.3s forwards;
  color: red;
}
  form{
    margin:4px;
    margin-top:0%;
    margin-left:   18%;
  }
  .input::placeholder {
    color: var(--font-color-sub);
    opacity: 0.8;
  }
  
  .input:focus {
    border: 2px solid var(--input-focus);
  }
 
.qq:hover{
    background-color: #000000;
    color: #e1dddd;
    
}
.qq{
    margin-left:26%;
    color:#000000;
    background-color: rgb(255, 247, 247);
}
.ok{
    display: flex;
    
    
}
.okright{
    margin-top:4%;
}
.okleft{
    margin-right:10%;
    margin-top:5%;
}
.file{
    margin-left: 0.2%;
    text-decoration: none;
   
}

  .h1{
    color: #ffffff;
    font-family:system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    margin-left:30%;
    margin-top: 3%;
    font-size: 30px;
    
  }
  .description{
    height:50%;
  }
  
  
  
  .loader-container{
  width:100%;
  height:100vh;
  background-color: #000000;
  position:fixed;
  
}
.loader{
  margin-left:47%;
  margin-top:18%;
  width:100px;
  height:100px;
  border:5px solid;
  color:#ffffff;
  border-radius:50%;
  border-top-color:transparent;
  animation:loader 1.2s linear infinite;


}
@keyframes loader{
    to{
      transform:rotate(360deg);
    }

  }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <body>
      <div class="loader-container">
        <div class="loader"></div>
      </div>
      <script>
        $(window).on("load",function(){
          $(".loader-container").fadeOut(1000);

        });
        </script>
        <header>
            <div class="logo"> Immobiler Manager</div>
            <div class="hamburger">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </div>
            <nav class="nav-navbar">
                <ul>
                <li>
                    <a href="{{ route('annonces.index') }}"  class="active">Home</a>
                </li>
               
                <li>
                    <a href="#">About</a>
                </li>
                
                
            
                </li>
                </ul>
            </nav>
           
            <div class="OK">

                <li>
                    
                    <img src="/SerieLaravel/public/photos/{{ auth()->user()->image }}" style="width:20%; height:80%;display:center;border-radius:50%;margin-left:70%;margin-top:2%; ">
                </li>
            </div>
        </header>
        <div class="card">
           
                
                
                <form id="form" enctype="multipart/form-data" action='{{route("annonces.store")}}' method="POST">
                    @csrf
                   <h1 class="bb">Postez votre Annonce</h4>
                   
                    <div class="ok">
                        <div class="okleft">
                        <p class="form-error" id="username_error"></p>
                        <div class="form-group">
        
                            <input id="name" type="text" name="name" placeholder="name" />
                        </div>
                        
                        <div class="form-group">
        
                            <input class="description" type="text" name="description" placeholder="description" />
                        </div>
                        <p class="form-error" id="password_error"></p>
                       
                        <div class="form-group">
        
                            <input id="prix" type="prix" name="prix" placeholder="prix" />
                        </div>
                    </div>
                    <div class="okright">
                        <p class="form-error" id="cpassword_error"></p>
                        <label>Choose Images</label>
                        <input  class="file" type="file" name="photos[]" multiple>
                        

 
                       
                        
                        <p class="form-error" id="cpassword_error"></p>
                        <div class="form-group">
        
                            <input id="surface" type="date" name="surface" />
                        </div>
                        <div class="form-group">
        
                            <input id="surface" type="surface" name="surface" placeholder="surface" />
                        </div>
                        <div class="form-group">
        
                            <input id="surface" type="adresse" name="adresse" placeholder="adresse" />
                        </div>
                    </div>
                    </div>
                        <div class="form-group">
                        <div class="submit-input">
                            <input class="qq" type="submit" value="Add" />
                        </div>
                        </div>
                    </div>
                    </form>

        </div>