<html>
    <head>
        <link rel="stylesheet" type="text/css" href="index1.css">
        <script src="https://kit.fontawesome.com/f770f9bca0.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&family=Satisfy&family=Shadows+Into+Light&family=Work+Sans:ital,wght@1,200&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/f770f9bca0.js" crossorigin="anonymous"></script>
<meta name="csrf-token" content="{{ csrf_token() }}">
<style>
    * {
    margin: 0;
    padding: 0;
    font-family: 'Dancing Script', cursive;
    font-family: 'Satisfy', cursive;
font-family: 'Shadows Into Light', cursive;
font-family: 'Work Sans', sans-serif;
    box-sizing: border-box;
}

body {
    background:aliceblue;

}
.kenburns-top {
	-webkit-animation: kenburns-top 5s ease-out both;
	        animation: kenburns-top 5s ease-out both;
   

}
.kenburns-top img{
    width: 100%;
    height: 90%;
    position:-ms-page;
}


header {
  
    width: 100%;
    height: 90px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    background-color:#000;
    padding: 0 100px;

}

.hamburger {
    display: none;
}

.logo {
    font-family: 'Dancing Script', cursive;
    font-family: 'Satisfy', cursive;
    font-size:30px;
    color: #fbfbfb;
    padding:0.1px;
    -webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
            animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    

}
/* ----------------------------------------------
 * Generated by Animista on 2023-1-28 14:50:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes logo {
    0% {
      -webkit-filter: blur(12px);
              filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
              filter: blur(0px);
      opacity: 1;
    }
  }
  @keyframes logo {
    0% {
      -webkit-filter: blur(12px);
              filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
              filter: blur(0px);
      opacity: 1;
    }
  }
  

nav ul li {

    display: inline-block;
    padding: 0px 18px;
}

nav ul li a {
    color: #fefefe;
    text-decoration: none;
    font-size: 20px;
    display: inline-block;
    border-radius: 23px;
    padding: 10 25px;
    margin: 0 3px;


}
nav ul li a:hover{
    color: black;
    background: #fefefe;

}
nav ul li a.active{
    color: black;
    background: #fefefe;

}
@media only screen and (max-width:1320px){
    header {
        padding:0 50px;
    }
}
@media only screen and(max-width:1100px){
    header {
        padding:0 30px;

    }
}
@media only screen and (max-width:900px){
    .hamburger{
        display:block;
        cursor:pointer;

    }
    .humberger .line{
        width:30px;
        height:3px;
        background: #fefefe;
        margin:6px 0;
    }
}
footer *{
    margin:0;
    padding:0;
    box-sizing: border-box;
}
.footer {
    z-index: -1;
    position: absolute;
    bottom:0;
    width: 100%;
    
    
    
  }
.container{
    z-index: -1;
    margin-bottom: 0%;
    height:170px;
    max-width: 1970px;
    margin:auto;
    background-color:#000000;
    padding-top: 20px;
  
}
.row{
    display: flex;
}
ul{
    list-style: none;
}
ul li a{

    text-decoration: none;
   
}

.lefside{
   
    
     padding-bottom: 6%;
}
.svg{
    opacity:0.4;
}
.cardimg{
    width:50%;
    height:80%;
    color: #000;
    margin-bottom: 0%;
    margin-left:100%;
    

}
.image-container {
    max-width: 100%;
    overflow-x: scroll;
    white-space: nowrap;
  }
  .image-container img {
  flex: 0 0 auto;
  scroll-snap-align: start; /* Optionnel - pour un défilement plus fluide */
}
.img {
    display: inline-block;
    height: 400px;
    width:60%;
    margin-right: 10px;
    margin-left:18%; /* Ajoute une marge droite entre les images pour les séparer */
  }
  .ourd{
    background-image: url("11.svg");
    background-size:300px; /* Ajuste la taille de l'image pour couvrir tout le corps */
    background-position: center;
  }
  .a{
    margin-left: 10%;
  }
  .rightside {
    float: right;
    width: 50%;
    background-size:380px; /* Ajuste la taille de l'image pour couvrir tout le corps */
    background-position: center;
    
    
  }
  .ism{
    font-family: 'Dancing Script';
    font-size: 160%;
    width:250px;
    margin-bottom:1%;
    border-radius: 20px;
 
    color: #0b0b0b;


  }
  .q{
    height:70%;
    width:30%;
    ;
    border-radius: 20px;
    padding-bottom:1%;
  }
  .font{
    font-size:30px;
  }
  .title{
    font-size:44px;
    margin-left:5px;
    margin-top: 10px;
    padding-bottom: 0%;
  

  }
  .z1{
    margin-left:10%;
  }
.h4{
   
    margin-bottom: 1%;
    display:flex;
}
h4{
  margin-bottom:23px;
  
  font-family: 'Nunito';
}
.okay{
    background-color: rgb(237, 229, 229);
    width:90%;
    height:100px;
    margin-left:5%;
    border-radius: 11px;
}

a{
  text-decoration: none;
  color: #000;
}
.oipo{
    border-radius: 50%;
    width:60px;
    height:50px;
    margin-top:2%;
}
.oip{
    border-radius: 50%;
    width:50px;
    height:50px;
    margin-top:2%;
}
.det1{
    display:flex;
}
.detail{
    display:flex;
    margin-right:65%;
}
.name{
    margin-top:2.5%;
}
h6{
    font-size:130%;
}

.loader-container{
  width:100%;
  height:100vh;
  background-color: #000000;
  position:fixed;
  
}
.v{
    margin-left:5%;
    margin-bottom:3%;
}
.ab{
    margin-top:1.5%;
    margin-left:10%;
    display:flex;
}
.liked{
    color:crimson;
}
.ww{
    margin-top:1%;
}
.p{
    margin-right:20%;
    height:70%;
    width:70%;
    
    
    
}
.c{
    display:flex;
}
.fyn{
    display:flex;
    
}
.m{
    margin-left:35%;
    margin-bottom:5%;
    margin-top:1%;
}
input {
  width: 290px;
  padding: 12px;
  border: none;
  border-radius: 4px;
  box-shadow: 2px 2px 7px 0 rgb(0, 0, 0, 0.2);
  outline: none;
  color: dimgray;
  margin-left: 34%;
}

input:invalid {
  animation: justshake 0.3s forwards;
  color: rgb(7, 7, 7);
}
.fa-heart{
    font-size: 160%;
}

.loader{
  margin-left:47%;
  margin-top:18%;
  width:100px;
  height:100px;
  border:5px solid;
  color:#ffffff;
  border-radius:50%;
  border-top-color:transparent;
  animation:loader 1.2s linear infinite;


}
@keyframes loader{
    to{
      transform:rotate(360deg);
    }

  }
  .ww{
    display:flex;
  }
  .t1{
    margin-top:3%;
  }
  .custom-alert {
        background-color: #f2f2f2;
        border: 1px solid #ccc;
        max-width: 400px;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 20px;
        font-weight: bold;
        color: rgb(0, 0, 0);
        margin-left:34%;
        margin-top:5%;
    }
    .z1{
    margin-left:10%;
    margin-top:5%;
    font-size:120%;
    margin-right:120%;
  }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <body>
      <div class="loader-container">
        <div class="loader"></div>
      </div>
      <script>
        $(window).on("load",function(){
          $(".loader-container").fadeOut(2000);

        });
        </script>
        <header>
            <div class="logo"> Immobiler Manager</div>
            <div class="hamburger">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </div>
            <nav class="nav-navbar">
                <ul>
                <li>
                    <a href="{{ route('annonces.index') }}" class="active">Home</a>
                </li>
                <li>
                    <a href="{{ route('profile.forg') }}">Settings</a>
                </li>
               
                <li>
                    <a href="{{ route('annonces.qwerty') }}">Dashboard</a>
                </li>
                
                
            
                </li>
                </ul>
                <div class="OK">
           
                    
                        
                </div>
                        
            </nav>
           
            
            
            </header>
            @if(session('success'))
            <div class="custom-alert"  id="custom-alert">
                {{ session('success') }}
            </div>
        @endif
        <script>
            // Attendre 3 secondes (3000 millisecondes) avant de fermer l'alerte
            setTimeout(function() {
                var alert = document.getElementById('custom-alert');
                if (alert) {
                    alert.style.display = 'none';
                }
            }, 2000);
        </script>
            
            <div class="page">
              <div class="fyn">
                <div class="detail">
                    <img src="/SerieLaravel/public/photos/{{$user->image}}"  class="oipo">
                    <div class="name"><h1>{{$user->name}}</h1></div>
                    
                  
                </div>
                <script>
                  

                    function likeIconClicked(annoncecode) {
                        console.log(annoncecode);
                        // Envoyer une requête AJAX au serveur pour effectuer l'action de like
                        $.ajax({
                            url: '{{ route('like', ['code' => $resultat->code]) }}',
                            method: 'POST',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            success: function(response) {
                                // Changer la couleur de l'icône en fonction de la réponse du serveur
                                if (response.liked) {
                                    // L'utilisateur a aimé, donc ajouter la classe CSS pour la couleur rouge
                                    $('#like-icon').addClass('liked');
                                    $("#test1").text(response.count);
                                  
                                  
                                } else {
                                    // L'utilisateur a annulé son like, donc supprimer la classe CSS pour la couleur rouge
                                    $('#like-icon').removeClass('liked');
                                    $("#test1").text(response.count);
                                   
                                    
                                    
                                }
                               
                              
                               
                            },
                            error: function(xhr, status, error) {
                                // Gérer les erreurs de la requête
                                console.log(error);
                            }
                        });
                    }
                </script> 
                <div class="ww"><i class="fa-solid fa-heart  "  onclick="likeIconClicked('{{ $resultat->code }}')" id="like-icon"></i><div id=test1 class="z1">{{$count}}</div><a href="{{Route('pdf',$resultat->code)}}"><i class="fa-solid fa-download font"></i></a></div>
                
         
        
            </div>
                </div>
                
                
                <div class="leftside"> 
                    

                    
                    <div class="image-container">
                        @foreach($images as $image)  
                        
                        <img src="/SerieLaravel/public/photos/{{$image->image}}" class="img">
                     
                        @endforeach
                    
                </div>
                
                      
                      
                      
                   
                   
                      



                </div>
                
               
            </div>
            <div class="ritside">
                <h4 class="title">{{ $resultat->name }}</h4>
                <div class="h4">
                    <div class="p">
                        <div class="x">
                        <h1 class="a">Description:</h1>
                        <h6 class="a">{{ $resultat->description }}</h6>
                        </div>
                        
                       
                    </div>
                    <div class="q">
                    
                    <h1 class="a">Prix</h1>
                <p class="a">{{ $resultat->prix }}.000dh</p>
                <h1 class="a">Surface</h1>
                <p class="a"> {{ $resultat->surface }}m2</p>
                <h1 class="a">Adresse</h1>
                <p class="a">{{ $resultat->adresse }}</p>
                <button class="ism a"><a href="{{ route('annonces.RDV', $resultat->code) }}" class="btn btn-warning btn-sm">RENDEZ-VOUS?</a></button>
                
                 
                
                </div>
                
               
        
                
                
                
                


            </div>
            <div class="comment">
                <form action="{{route("comment.store")}}" method="POST">
                    @csrf
                    <input type="hidden" name="code" value="{{ $resultat->code}}">
                <input type="text" name="comment" placeholder="Votre Commentaire ici..." ><br>
                
                
                </form>
                @if($res->isEmpty())
                    <p class="m">Pas de Commentaire actuellement<p>
                @endif
                        @foreach ($res as $r)
                        <div class="info">
                            <div class="det">
                            <div class="det1">
                            <div class="detail">
                                <img src="/SerieLaravel/public/photos/{{$r['image']}}"  class="oip">
                                <div class="name"><h1>{{$r['name']}}</h1></div>
                         
                            </div>
                            <div class="ab"><div class="z">{{ $r['created_at']->format('H:i') }}</div>
                            
                            <a href="{{ route('comment.dest', $r->id) }}" class="btn btn-warning btn-sm"><i class="fa-solid fa-trash c"></i></a>
                            </div>
                        </div>
            
                            <h3 class="v">{{$r['content']}}<h3>
                        </div>
                        </div>
                            
                        @endforeach
            </div>
         

           
                    
                      




    </body>
</html>